# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: 🤞Build with Maven
      run: mvn --batch-mode --update-snapshots test jacoco:report --fail-at-end
    - name: 👀Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: ${{ always() }}
    - name: 🚀 Coveralls Coverage Report Submission
      run: mvn coveralls:report --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }}
             - name: refresh coverage badge
             uses: fjogeleit/http-request-action@master
             with:
               url: https://camo.githubusercontent.com/25c48952fd37d3a2c0e5a94b39667f98157e9333ab41c815990bb25df5e46af3/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f667265656261747469652f5961747a692f62616467652e7376673f266b696c6c5f63616368653d316272616e63683d6d61696e
               method: PURGE





